architect:
- yegor256
- dmarkov
install:
- sudo gem install pdd
assets:
  secring.gpg: yegor256/home#assets/secring.gpg
  settings.xml: yegor256/home#assets/jcabi/settings.xml
  pubring.gpg: yegor256/home#assets/pubring.gpg
  s3cfg: yegor256/home#assets/s3cfg
merge:
  script: |-
    mvn clean install -Pqulice --errors --settings ../settings.xml
    mvn clean
    pdd --source=$(pwd) --verbose --file=/dev/null
  commanders:
  - caarlos0
  - carlosmiranda
  - darkled
  - dmzaytsev
  - ggajos
  - krzyk
  - longtimeago
  - mkordas
  - pinaf
deploy:
  script: |-
    mvn clean deploy -Pqulice --errors --settings ../settings.xml
    mvn clean
    pdd --source=$(pwd) --verbose --file=jcabi-manifests.xml
    s3cmd --no-progress put jcabi-manifests.xml --config=../s3cfg s3://pdd.teamed.io/jcabi-manifests.xml
env:
  MAVEN_OPTS: -XX:MaxPermSize=256m -Xmx1g
release:
  script: |-
    if [ -n ${snapshot} ]; then
      echo 'Please specify next snapshot version, e.g. @rultor release, tag=`2.0`, snapshot=`2.1-SNAPSHOT`'
      exit 1
    fi
    mvn versions:set "-DnewVersion=${tag}"
    sed -i "s|<snapshotVersion>.*</snapshotVersion>|<snapshotVersion>${nextSnapshotVersion}</snapshotVersion>|" pom.xml
    git commit -am "${tag}"
    mvn clean deploy -Pqulice -Psonatype -Pjcabi --errors --settings ../settings.xml
    mvn clean site-deploy -Psite --errors --settings ../settings.xml
  commanders:
  - yegor256