assets:
  settings.xml: "yegor256/home#assets/jcabi/settings.xml"
  pubring.gpg: "yegor256/home#assets/pubring.gpg"
  secring.gpg: "yegor256/home#assets/secring.gpg"
  s3cfg: "yegor256/home#assets/s3cfg"

env:
  MAVEN_OPTS: "-XX:MaxPermSize=256m -Xmx1g"

install:
  - "sudo gem install pdd"

merge:
  script:
    - "mvn clean install -Pqulice --errors --settings ../settings.xml"
    - "mvn clean"
    - "pdd --source=$(pwd) --verbose --file=/dev/null"

deploy:
  script:
    - "mvn clean deploy -Pqulice --errors --settings ../settings.xml"
    - "mvn clean"
    - "pdd --source=$(pwd) --verbose --file=jcabi-manifests.xml"
    - "s3cmd --no-progress put jcabi-manifests.xml --config=../s3cfg s3://pdd.teamed.io/jcabi-manifests.xml"

release:
  script:
    - "if [ -n ${nextSnapshotVersion} ]; then echo 'Please specify next snapshot version, e.g. @rultor release, tag=`2.0`, nextSnapshotVersion=`2.1-SNAPSHOT`'; exit 1; fi"
    - "mvn versions:set \"-DnewVersion=${tag}\""
    - "sed 's/<snapshotVersion>.*<\/snapshotVersion>/<snapshotVersion>3.0-SNAPSHOT<\/snapshotVersion>/' pom.xml > pom.xml.new"
    - "mv pom.xml.new pom.xml"
    - "git commit -am \"${tag}\""
    - "mvn clean deploy -Pqulice -Psonatype -Pjcabi --errors --settings ../settings.xml"
    - "mvn clean site-deploy -Psite --errors --settings ../settings.xml"
